trigger: none
pr: none
schedules:
  - cron: "0 3 * * *"
    displayName: Daily build at 03:00 AM
    always: true
    branches:
      include:
        - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: "DataModel"
  - name: bicepTemplateFile
    value: "Infrastructure/main.bicep"

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: BuildApp
        displayName: "Build App"
        steps:
          - template: azure-pipelines-build-jobs.yml
            parameters:
              bicepTemplateFile: $(bicepTemplateFile)
              azureTenantId: $(AzureTenantId)
              azureClientId: $(AzureClientId)
              azureClientSecret: $(AzureClientSecret)
              dataverseUrl: $(DataverseUrl)

  - stage: Deploy
    displayName: "Deploy Stage"
    dependsOn: Build
    jobs:
      - job: DeployApp
        displayName: "Deploy App"
        steps:
          - template: azure-pipelines-deploy-jobs.yml
            parameters:
              bicepTemplateFile: $(bicepTemplateFile)
              azureServiceConnectionName: $(AzureServiceConnectionName)
              azureResourceGroupName: $(AzureResourceGroupName)
              azureLocation: $(AzureLocation)
              websitePassword: $(WebsitePassword)
              websiteSessionSecret: $(WebsiteSessionSecret)
              websiteName: $(WebsiteName)
