trigger: none
pr: none
schedules:
  - cron: "0 3 * * *"
    displayName: Daily build at 03:00 AM
    always: true
    branches:
      include:
        - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: "DataModel"
  - name: bicepTemplateFile
    value: "Infrastructure/main.bicep"

stages:
- template: azure-pipelines-steps.yml
  parameters:
    bicepTemplateFile: $(bicepTemplateFile)
    azureServiceConnectionName: $(AzureServiceConnectionName)
    azureResourceGroupName: $(AzureResourceGroupName)
    azureLocation: $(AzureLocation)
    websitePassword: $(WebsitePassword)
    websiteSessionSecret: $(WebsiteSessionSecret)
    websiteName: $(WebsiteName)
    azureTenantId: $(AzureTenantId)
    azureClientId: $(AzureClientId)
    azureClientSecret: $(AzureClientSecret)
    dataverseUrl: $(DataverseUrl)
