import Section from "./Section"
function List() {
    return <>
<Section name="Account">
        <p  className="py-2 border-b-2">By</p>
        <p  className="py-2 border-b-2">Address1_City</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Adresse</p>
        <p  className="py-2 border-b-2">Address1_Line1</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Stednavn</p>
        <p  className="py-2 border-b-2">Address1_Line2</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type the second line of the primary address.</p>
        <p  className="py-2 border-b-2">Postnr.</p>
        <p  className="py-2 border-b-2">Address1_PostalCode</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type the ZIP Code or postal code for the primary address.</p>
        <p  className="py-2 border-b-2">Oprettet</p>
        <p  className="py-2 border-b-2">CreatedOn</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Masseudsendelse af mails</p>
        <p  className="py-2 border-b-2">DoNotBulkEMail</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Masseudsendelse af mails</p>
        <p  className="py-2 border-b-2">Do not allow Bulk Mails</p>
        <p  className="py-2 border-b-2">DoNotBulkPostalMail</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Select whether the account allows bulk postal mail sent through marketing campaigns or quick campaigns. If Do Not Allow is selected, the account can be added to marketing lists, but will be excluded from the postal mail.</p>
        <p  className="py-2 border-b-2">Mail</p>
        <p  className="py-2 border-b-2">DoNotEMail</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Opkald</p>
        <p  className="py-2 border-b-2">DoNotPhone</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Do not allow Mails</p>
        <p  className="py-2 border-b-2">DoNotPostalMail</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Select whether the account allows direct mail. If Do Not Allow is selected, the account will be excluded from letter activities distributed in marketing campaigns.</p>
        <p  className="py-2 border-b-2">Mailadresse</p>
        <p  className="py-2 border-b-2">EMailAddress1</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Follow Email Activity</p>
        <p  className="py-2 border-b-2">FollowEmail</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Information about whether to allow following email activity like opens, attachment views and link clicks for emails sent to the account.</p>
        <p  className="py-2 border-b-2">Enhedstype</p>
        <p  className="py-2 border-b-2">msys_AccountType</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Enhed Valideret</p>
        <p  className="py-2 border-b-2">msys_AccountValidated</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Kommune</p>
        <p  className="py-2 border-b-2">msys_Addess1Municipality</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">By</p>
        <p  className="py-2 border-b-2">msys_Address1City</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">C/O</p>
        <p  className="py-2 border-b-2">msys_Address1CO</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Etage</p>
        <p  className="py-2 border-b-2">msys_Address1Floor</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Evt. etage betegnelse ellers ”blank”. Etage skal følge syntaksen 'kl', 'st', '01', '02', '03', ….'99'.</p>
        <p  className="py-2 border-b-2">Husbogstav</p>
        <p  className="py-2 border-b-2">msys_Address1HouseLetter</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Modtagerens eventuelle husbogstav. Ellers ”blank”.</p>
        <p  className="py-2 border-b-2">Husnummer</p>
        <p  className="py-2 border-b-2">msys_Address1HouseNumber</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Placering</p>
        <p  className="py-2 border-b-2">msys_Address1LocationOnFloor</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Evt. placering på etage ellers ”blank”. Placering skal følge syntaksen 'tv ', 'th ', 'mf '. Hvis der er mere end fire afleveringssteder på samme etage, navngives placeringen fra venstre mod højre med angivelse af '0001', '0002', '0003', … '9999'. Eller ’A01’, ’A02’, … etc.</p>
        <p  className="py-2 border-b-2">Manuel Adresseindtastning</p>
        <p  className="py-2 border-b-2">msys_Address1ManualAddress</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Postnummer</p>
        <p  className="py-2 border-b-2">msys_Address1Postalcode</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Region</p>
        <p  className="py-2 border-b-2">msys_Address1Region</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Gadenavn</p>
        <p  className="py-2 border-b-2">msys_Address1StreetName</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Navn på gade eller vej.</p>
        <p  className="py-2 border-b-2">Land</p>
        <p  className="py-2 border-b-2">msys_Adresse1Country</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Rykkersag</p>
        <p  className="py-2 border-b-2">msys_ArrearsCase</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Selskabsform</p>
        <p  className="py-2 border-b-2">msys_CompanyForm</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">CVR-nr.</p>
        <p  className="py-2 border-b-2">msys_CvrNum</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">CVR Status</p>
        <p  className="py-2 border-b-2">msys_CvrValidationStatus</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Debitor</p>
        <p  className="py-2 border-b-2">msys_Debtor</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">ZZ_EAN-nr.</p>
        <p  className="py-2 border-b-2">msys_EanNum</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Enhedsnummer</p>
        <p  className="py-2 border-b-2">msys_Enhedsnummer</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Firmakode</p>
        <p  className="py-2 border-b-2">msys_ERPCompanyCode</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Omkostningssted</p>
        <p  className="py-2 border-b-2">msys_ERPCostLocation</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Finanstype</p>
        <p  className="py-2 border-b-2">msys_ERPType</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Afmeldingskvittering</p>
        <p  className="py-2 border-b-2">msys_EventCancellationReceipt</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Invitation </p>
        <p  className="py-2 border-b-2">msys_EventInvite</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Kun relevant hvis der udsendes invitationer til dette arrangement. Overstyrer foreningens standardskabelon til dette, kan overstyres på den enkelte invitation.</p>
        <p  className="py-2 border-b-2">Tilmeldingskvittering (tilmeldt)</p>
        <p  className="py-2 border-b-2">msys_EventSignupReceipt</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Tilmeldingskvittering (venteliste)</p>
        <p  className="py-2 border-b-2">msys_EventSignupWaitlist</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Sendes til deltagere, der får en plads på venteliste. </p>
        <p  className="py-2 border-b-2">Ventelistetilbud</p>
        <p  className="py-2 border-b-2">msys_EventWaitingListOffer</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Oprykning fra venteliste</p>
        <p  className="py-2 border-b-2">msys_EventWaitingListPromotion</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Skjul på selvbetjening  </p>
        <p  className="py-2 border-b-2">msys_HideOnSelfservice</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Blokeret for opkrævning</p>
        <p  className="py-2 border-b-2">msys_InvoicingBlocked</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Sidst opdateret fra CVR</p>
        <p  className="py-2 border-b-2">msys_LastModifiedFromCVR</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">M4Id</p>
        <p  className="py-2 border-b-2">msys_M4Id</p>
        <p  className="py-2 border-b-2">IntegerType</p>
        <p  className="py-2 border-b-2">The primary key of the Enhed in M4</p>
        <p  className="py-2 border-b-2">Godkend enhed uden CVR-nr.</p>
        <p  className="py-2 border-b-2">msys_NoCvrNum</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Ejerkonstruktion</p>
        <p  className="py-2 border-b-2">msys_OwnershipStructure</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Uddannelsessted</p>
        <p  className="py-2 border-b-2">msys_PlaceOfEducation</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">P-nr.</p>
        <p  className="py-2 border-b-2">msys_PNum</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Praksisstart</p>
        <p  className="py-2 border-b-2">msys_PracticeStart</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Primær Betalingsaftale</p>
        <p  className="py-2 border-b-2">msys_PrimaryPaymentAgreement</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">FS Standardrolle</p>
        <p  className="py-2 border-b-2">msys_ProSocietyDefaultRole</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Offentligt Tilgængeligt</p>
        <p  className="py-2 border-b-2">msys_PublicAvailable</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Kun relevant for Faglige Selskaber. Angiver om det Faglige Selskab er "offentligt tilgængeligt" og derfor kan fremsøges på selvbetjeningen.</p>
        <p  className="py-2 border-b-2">Hent informationer fra CVR</p>
        <p  className="py-2 border-b-2">msys_RerunUpdateCVR</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">UVM-nr.</p>
        <p  className="py-2 border-b-2">msys_UvmNum</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Valideret CVR</p>
        <p  className="py-2 border-b-2">msys_ValidCVR</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Arbejdspladstype</p>
        <p  className="py-2 border-b-2">msys_WorkplaceType</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Navn</p>
        <p  className="py-2 border-b-2">Name</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type the company or business name.</p>
        <p  className="py-2 border-b-2">Record Created On</p>
        <p  className="py-2 border-b-2">OverriddenCreatedOn</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Date and time that the record was migrated.</p>
        <p  className="py-2 border-b-2">Overordnet enhed</p>
        <p  className="py-2 border-b-2">ParentAccountId</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Choose the parent account associated with this account to show parent and child businesses in reporting and analytics.</p>
        <p  className="py-2 border-b-2">Kontaktmetode</p>
        <p  className="py-2 border-b-2">PreferredContactMethodCode</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Primary Contact</p>
        <p  className="py-2 border-b-2">PrimaryContactId</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Choose the primary contact for the account to provide quick access to contact details.</p>
        <p  className="py-2 border-b-2">Status</p>
        <p  className="py-2 border-b-2">StateCode</p>
        <p  className="py-2 border-b-2">StateType</p>
        <p  className="py-2 border-b-2">Shows whether the account is active or inactive. Inactive accounts are read-only and can't be edited unless they are reactivated.</p>
        <p  className="py-2 border-b-2">Telefonnummer</p>
        <p  className="py-2 border-b-2">Telephone1</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
</Section>
<Section name="Appointment">
        <p  className="py-2 border-b-2">Møde</p>
        <p  className="py-2 border-b-2">ActivityId</p>
        <p  className="py-2 border-b-2">UniqueidentifierType</p>
        <p  className="py-2 border-b-2">Unique identifier of the appointment.</p>
        <p  className="py-2 border-b-2">Created On</p>
        <p  className="py-2 border-b-2">CreatedOn</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.</p>
        <p  className="py-2 border-b-2">Location</p>
        <p  className="py-2 border-b-2">Location</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type the location where the appointment will take place, such as a conference room or customer office.</p>
        <p  className="py-2 border-b-2">Aktivitetskategori</p>
        <p  className="py-2 border-b-2">msys_ActivityCategory</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Medlem ved oprettelse</p>
        <p  className="py-2 border-b-2">msys_MemberOnCreate</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Mødedeltager</p>
        <p  className="py-2 border-b-2">requiredattendees</p>
        <p  className="py-2 border-b-2">PartyListType</p>
        <p  className="py-2 border-b-2">Liste over nødvendige deltagere i denne aktivitet.</p>
        <p  className="py-2 border-b-2">Subject</p>
        <p  className="py-2 border-b-2">Subject</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type a short description about the objective or primary topic of the appointment.</p>
</Section>
<Section name="BusinessUnit">
        <p  className="py-2 border-b-2">Er forening</p>
        <p  className="py-2 border-b-2">msys_IsAssociation</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Definerer om denne forretningsenhed er en forening (man kan være medlem af) eller ej.</p>
</Section>
<Section name="Contact">
        <p  className="py-2 border-b-2">Account</p>
        <p  className="py-2 border-b-2">AccountId</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Unique identifier of the account with which the contact is associated.</p>
        <p  className="py-2 border-b-2">Hjemmeadresse: By</p>
        <p  className="py-2 border-b-2">Address1_City</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Adresse</p>
        <p  className="py-2 border-b-2">Address1_Line1</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Angiv den første linje i den primære adresse.</p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Stednavn</p>
        <p  className="py-2 border-b-2">Address1_Line2</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Angiv den anden linje i den primære adresse.</p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Postnummer</p>
        <p  className="py-2 border-b-2">Address1_PostalCode</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type the ZIP Code or postal code for the primary address.</p>
        <p  className="py-2 border-b-2">Leveringsadresse: By</p>
        <p  className="py-2 border-b-2">Address2_City</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type the city for the secondary address.</p>
        <p  className="py-2 border-b-2">Leveringsadresse: Adresse</p>
        <p  className="py-2 border-b-2">Address2_Line1</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Leveringsadresse: Stednavn</p>
        <p  className="py-2 border-b-2">Address2_Line2</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Leveringsadresse: Postnummer</p>
        <p  className="py-2 border-b-2">Address2_PostalCode</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type the ZIP Code or postal code for the secondary address.</p>
        <p  className="py-2 border-b-2">Faktureringsadresse: By</p>
        <p  className="py-2 border-b-2">Address3_City</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type the city for the 3rd address.</p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Adresse</p>
        <p  className="py-2 border-b-2">Address3_Line1</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">the first line of the 3rd address.</p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Stednavn</p>
        <p  className="py-2 border-b-2">Address3_Line2</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Postnummer</p>
        <p  className="py-2 border-b-2">Address3_PostalCode</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Fødselsdato</p>
        <p  className="py-2 border-b-2">BirthDate</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Masseudsendelse af mails </p>
        <p  className="py-2 border-b-2">DoNotBulkEMail</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Viser om personen accepterer masseudsendlese af emails sendt gennem markedsføringskampagner. Hvis ikke "Tillad" vælges, vil personen blive udelukket mailen.</p>
        <p  className="py-2 border-b-2">Mail</p>
        <p  className="py-2 border-b-2">DoNotEMail</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Tillad emails</p>
        <p  className="py-2 border-b-2">Opkald</p>
        <p  className="py-2 border-b-2">DoNotPhone</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Tillad opkald</p>
        <p  className="py-2 border-b-2">Primær mailadresse</p>
        <p  className="py-2 border-b-2">EMailAddress1</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Mailadresse for særlig rolle</p>
        <p  className="py-2 border-b-2">EMailAddress2</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">E-mailadresse for særlig rolle. </p>
        <p  className="py-2 border-b-2">Arbejdsmailadresse</p>
        <p  className="py-2 border-b-2">EMailAddress3</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Arbejdsmailadresse.</p>
        <p  className="py-2 border-b-2">Entity Image</p>
        <p  className="py-2 border-b-2">EntityImage</p>
        <p  className="py-2 border-b-2">ImageType</p>
        <p  className="py-2 border-b-2">Shows the default image for the record.</p>
        <p  className="py-2 border-b-2">Fornavn</p>
        <p  className="py-2 border-b-2">FirstName</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Navn</p>
        <p  className="py-2 border-b-2">FullName</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Kombination af personens fornavn og efternavn. </p>
        <p  className="py-2 border-b-2">Køn</p>
        <p  className="py-2 border-b-2">GenderCode</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Efternavn</p>
        <p  className="py-2 border-b-2">LastName</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Middle Name</p>
        <p  className="py-2 border-b-2">MiddleName</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type the contact's middle name or initial to make sure the contact is addressed correctly.</p>
        <p  className="py-2 border-b-2">Telefonnummer</p>
        <p  className="py-2 border-b-2">MobilePhone</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Mobiltelefonnummer.</p>
        <p  className="py-2 border-b-2">Konto nr.</p>
        <p  className="py-2 border-b-2">msys_AccounNum</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Kommune</p>
        <p  className="py-2 border-b-2">msys_Addess1Municipality</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Leveringsadresse: Kommune</p>
        <p  className="py-2 border-b-2">msys_Addess2Municipality</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Kommune</p>
        <p  className="py-2 border-b-2">msys_Addess3Municipality</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Hjemmeadresse: By (Opslag)</p>
        <p  className="py-2 border-b-2">msys_Address1City</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Hjemmeadresse: C/O</p>
        <p  className="py-2 border-b-2">msys_Address1CO</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Etage</p>
        <p  className="py-2 border-b-2">msys_Address1Floor</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Evt. etage betegnelse ellers ”blank”. Etage skal følge syntaksen 'kl', 'st', '01', '02', '03', ….'99'.</p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Husbogstav</p>
        <p  className="py-2 border-b-2">msys_Address1HouseLetter</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Modtagerens eventuelle husbogstav. Ellers ”blank”.</p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Husnummer</p>
        <p  className="py-2 border-b-2">msys_Address1HouseNumber</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Modtagerens husnummer.</p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Placering</p>
        <p  className="py-2 border-b-2">msys_Address1LocationOnFloor</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Evt. placering på etage ellers ”blank”. Placering skal følge syntaksen 'tv ', 'th ', 'mf '. Hvis der er mere end fire afleveringssteder på samme etage, navngives placeringen fra venstre mod højre med angivelse af '0001', '0002', '0003', … '9999'. Eller ’A01’, ’A02’, … etc.</p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Manuel Adresseindtastning</p>
        <p  className="py-2 border-b-2">msys_Address1ManualAddress</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Sættes til ”Ja” hvis det skal være muligt at manuelt indtaste adressefelter fremfor at vælge blandt i liste. Bør som udgangspunkt kun udfyldes, hvis der er tale om et udenlandsk postnummer som ikke findes i systemet.</p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Postnummer (Opslag)</p>
        <p  className="py-2 border-b-2">msys_Address1Postalcode</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Region</p>
        <p  className="py-2 border-b-2">msys_Address1Region</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Gadenavn</p>
        <p  className="py-2 border-b-2">msys_Address1StreetName</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Navn på gade eller vej.</p>
        <p  className="py-2 border-b-2">Leveringsadresse: By (Opslag)</p>
        <p  className="py-2 border-b-2">msys_Address2City</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Leveringsadresse: C/O</p>
        <p  className="py-2 border-b-2">msys_Address2CO</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Leveringsadresse: Etage</p>
        <p  className="py-2 border-b-2">msys_Address2Floor</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Evt. etage betegnelse ellers ”blank”. Etage skal følge syntaksen 'kl', 'st', '01', '02', '03', ….'99'.</p>
        <p  className="py-2 border-b-2">Leveringsadresse: Husbogstav</p>
        <p  className="py-2 border-b-2">msys_Address2HouseLetter</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Modtagerens eventuelle husbogstav. Ellers ”blank”.</p>
        <p  className="py-2 border-b-2">Leveringsadresse: Husnummer</p>
        <p  className="py-2 border-b-2">msys_Address2HouseNumber</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Leveringsadresse: Placering</p>
        <p  className="py-2 border-b-2">msys_Address2LocationOnFloor</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Evt. placering på etage ellers ”blank”. Placering skal følge syntaksen 'tv ', 'th ', 'mf '. Hvis der er mere end fire afleveringssteder på samme etage, navngives placeringen fra venstre mod højre med angivelse af '0001', '0002', '0003', … '9999'. Eller ’A01’, ’A02’, … etc.</p>
        <p  className="py-2 border-b-2">Leveringsadresse: Manuel Adresseindtastning</p>
        <p  className="py-2 border-b-2">msys_Address2ManualAddress</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Leveringsadresse: Postnummer (Opslag)</p>
        <p  className="py-2 border-b-2">msys_Address2Postalcode</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Leveringsadresse: Region</p>
        <p  className="py-2 border-b-2">msys_Address2Region</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Leveringsadresse: Gadenavn</p>
        <p  className="py-2 border-b-2">msys_Address2StreetName</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Navn på gade eller vej.</p>
        <p  className="py-2 border-b-2">Faktureringsadresse: By (Opslag)</p>
        <p  className="py-2 border-b-2">msys_Address3City</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Faktureringsadresse: C/O</p>
        <p  className="py-2 border-b-2">msys_Address3CO</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Etage</p>
        <p  className="py-2 border-b-2">msys_Address3Floor</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Evt. etage betegnelse ellers ”blank”. Etage skal følge syntaksen 'kl', 'st', '01', '02', '03', ….'99'.</p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Husbogstav</p>
        <p  className="py-2 border-b-2">msys_Address3HouseLetter</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Modtagerens eventuelle husbogstav. Ellers ”blank”.</p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Husnummer</p>
        <p  className="py-2 border-b-2">msys_Address3HouseNumber</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Placering</p>
        <p  className="py-2 border-b-2">msys_Address3LocationOnFloor</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Evt. placering på etage ellers ”blank”. Placering skal følge syntaksen 'tv ', 'th ', 'mf '. Hvis der er mere end fire afleveringssteder på samme etage, navngives placeringen fra venstre mod højre med angivelse af '0001', '0002', '0003', … '9999'. Eller ’A01’, ’A02’, … etc.</p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Manuel Adresseindtastning</p>
        <p  className="py-2 border-b-2">msys_Address3ManualAddress</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Postnummer (Opslag)</p>
        <p  className="py-2 border-b-2">msys_Address3Postalcode</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Region</p>
        <p  className="py-2 border-b-2">msys_Address3Region</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Gadenavn</p>
        <p  className="py-2 border-b-2">msys_Address3StreetName</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Navn på gade eller vej.</p>
        <p  className="py-2 border-b-2">Hjemmeadresse: Land</p>
        <p  className="py-2 border-b-2">msys_Adresse1Country</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Leveringsadresse: Land</p>
        <p  className="py-2 border-b-2">msys_Adresse2Country</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Faktureringsadresse: Land</p>
        <p  className="py-2 border-b-2">msys_Adresse3Country</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Alder</p>
        <p  className="py-2 border-b-2">msys_Age</p>
        <p  className="py-2 border-b-2">DecimalType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Find Kollega</p>
        <p  className="py-2 border-b-2">msys_AllowFindColleague</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Tillad Find Kollega</p>
        <p  className="py-2 border-b-2">Rykkersag</p>
        <p  className="py-2 border-b-2">msys_ArrearsCase</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">CPR nr.</p>
        <p  className="py-2 border-b-2">msys_Cpr</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">CVR ej Praksis</p>
        <p  className="py-2 border-b-2">msys_CvrNonPractice</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Dadlnet-mail</p>
        <p  className="py-2 border-b-2">msys_Dadlnetmail</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Slettedato</p>
        <p  className="py-2 border-b-2">msys_DeletionDate</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Kommende dag for hvornår personen vil blive slettet automatisk af GDRP-slettejobbet. Personen slettes kun, hvis alle krav for sletning er opfyldt, også selvom der allerede er sat en dato. </p>
        <p  className="py-2 border-b-2">Leveres til</p>
        <p  className="py-2 border-b-2">msys_DeliveryAddressOpt</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2">Vælg hvilken adresse f.eks. Ugeskrift for Læger skal leveres til. </p>
        <p  className="py-2 border-b-2">Levering</p>
        <p  className="py-2 border-b-2">msys_DeliveryOptInOut</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Årsag for inaktiv levering</p>
        <p  className="py-2 border-b-2">msys_DeliveryStopReason</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Uddannelsessted</p>
        <p  className="py-2 border-b-2">msys_EducationPlace</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Uddannelsesdato</p>
        <p  className="py-2 border-b-2">msys_EducationStartDate</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">E-mailadresse 4</p>
        <p  className="py-2 border-b-2">msys_EMailAdresse4</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Dadlnet-mailadresse. </p>
        <p  className="py-2 border-b-2">FarPayCustomerNumber</p>
        <p  className="py-2 border-b-2">msys_FarPayCustomerNumber</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Kan midlertidigt opbevare et kundenummer til en FarPay betalingsaftale i forbindelse med indmeldelse af et nyt medlem. </p>
        <p  className="py-2 border-b-2">Dimittenddato</p>
        <p  className="py-2 border-b-2">msys_GraduationDate</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Blokeret for opkrævning</p>
        <p  className="py-2 border-b-2">msys_InvoicingBlocked</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Seneste login på selvbetjeningen</p>
        <p  className="py-2 border-b-2">msys_lastlogintoselfservice</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Seneste tidspunkt for login i selvbetjeningen</p>
        <p  className="py-2 border-b-2">M4Id</p>
        <p  className="py-2 border-b-2">msys_M4Id</p>
        <p  className="py-2 border-b-2">IntegerType</p>
        <p  className="py-2 border-b-2">The primary key of the person in M4</p>
        <p  className="py-2 border-b-2">Autorisationsdato</p>
        <p  className="py-2 border-b-2">msys_MedicalLicenseDate</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Slutdato for autorisations-ID</p>
        <p  className="py-2 border-b-2">msys_MedicalLicenseEndDate</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Den dato hvor det i medlemsystemet er blevet registreret at personens autorisations ID ikke længere er gyldigt. Det er ikke nødvendigvis den præcise dato for hvornår autorisationen blev tilbagetrukket.</p>
        <p  className="py-2 border-b-2">Autorisations-ID</p>
        <p  className="py-2 border-b-2">msys_MedicalLicenseId</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Autorisation gyldig</p>
        <p  className="py-2 border-b-2">msys_MedicalLicenseValid</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Hvis sat til “Ja” har personen en gyldig autorisation</p>
        <p  className="py-2 border-b-2">Udmeldelsesårsag</p>
        <p  className="py-2 border-b-2">msys_MembershipCancellationReason</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Medlemsnummer</p>
        <p  className="py-2 border-b-2">msys_MembershipId</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">MitId Uuid</p>
        <p  className="py-2 border-b-2">msys_MitIdUuid</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">NemKonto</p>
        <p  className="py-2 border-b-2">msys_NemKonto</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Persontype</p>
        <p  className="py-2 border-b-2">msys_PersonType</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Primær betalingsaftale</p>
        <p  className="py-2 border-b-2">msys_PrimaryPaymentAgreement</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Primær Forening</p>
        <p  className="py-2 border-b-2">msys_PrimaryUnion</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Primær Arbejdsplads</p>
        <p  className="py-2 border-b-2">msys_PrimaryWorkplace</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Vis Profilbillede Offentligt</p>
        <p  className="py-2 border-b-2">msys_ProfileImagePublicAvailable</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Tillad at vise profilbillede offentligt, f.eks. visning af udvalgsmedlemmer på Læger.dk</p>
        <p  className="py-2 border-b-2">Vis Profil Offentligt</p>
        <p  className="py-2 border-b-2">msys_ProfilePublicAvailable</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Tillad at profilen bruges i offentlige sider, f.eks. visning af udvalgsmedlemmer på Læger.dk</p>
        <p  className="py-2 border-b-2">Udmeldelsesårsag</p>
        <p  className="py-2 border-b-2">msys_ReasonForWithdrawal</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Reg. nr.</p>
        <p  className="py-2 border-b-2">msys_RegNum</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Robinsonflag</p>
        <p  className="py-2 border-b-2">msys_RobinsonRegister</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Ukendt adresse</p>
        <p  className="py-2 border-b-2">msys_UnknownAddress</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Hemmeligt tlf. nr. </p>
        <p  className="py-2 border-b-2">msys_UnknownPhoneNumber</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Verification Token</p>
        <p  className="py-2 border-b-2">msys_VerificationToken</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Udmeldelsesdato</p>
        <p  className="py-2 border-b-2">msys_WithdrawalDate</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Company Name</p>
        <p  className="py-2 border-b-2">ParentCustomerId</p>
        <p  className="py-2 border-b-2">CustomerType</p>
        <p  className="py-2 border-b-2">Select the parent account or parent contact for the contact to provide a quick link to additional details, such as financial information, activities, and opportunities.</p>
        <p  className="py-2 border-b-2">Kontaktmetode </p>
        <p  className="py-2 border-b-2">PreferredContactMethodCode</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Status</p>
        <p  className="py-2 border-b-2">StateCode</p>
        <p  className="py-2 border-b-2">StateType</p>
        <p  className="py-2 border-b-2">Shows whether the contact is active or inactive. Inactive contacts are read-only and can't be edited unless they are reactivated.</p>
        <p  className="py-2 border-b-2">Business Phone</p>
        <p  className="py-2 border-b-2">Telephone1</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type the main phone number for this contact.</p>
</Section>
<Section name="Email">
        <p  className="py-2 border-b-2">Duration</p>
        <p  className="py-2 border-b-2">ActualDurationMinutes</p>
        <p  className="py-2 border-b-2">IntegerType</p>
        <p  className="py-2 border-b-2">Type the number of minutes spent creating and sending the email. The duration is used in reporting.</p>
        <p  className="py-2 border-b-2">Bcc</p>
        <p  className="py-2 border-b-2">bcc</p>
        <p  className="py-2 border-b-2">PartyListType</p>
        <p  className="py-2 border-b-2">Enter the recipients that are included on the email distribution, but are not displayed to other recipients.</p>
        <p  className="py-2 border-b-2">Category</p>
        <p  className="py-2 border-b-2">Category</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type a category to identify the email type, such as lead outreach, customer follow-up, or service alert, to tie the email to a business group or function.</p>
        <p  className="py-2 border-b-2">Cc</p>
        <p  className="py-2 border-b-2">cc</p>
        <p  className="py-2 border-b-2">PartyListType</p>
        <p  className="py-2 border-b-2">Enter the recipients that should be copied on the email.</p>
        <p  className="py-2 border-b-2">Created By</p>
        <p  className="py-2 border-b-2">CreatedBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Shows who created the record.</p>
        <p  className="py-2 border-b-2">Created On</p>
        <p  className="py-2 border-b-2">CreatedOn</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.</p>
        <p  className="py-2 border-b-2">Created By (Delegate)</p>
        <p  className="py-2 border-b-2">CreatedOnBehalfBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Shows who created the record on behalf of another user.</p>
        <p  className="py-2 border-b-2">Send Later</p>
        <p  className="py-2 border-b-2">DelayedEmailSendTime</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Enter the expected date and time when email will be sent.</p>
        <p  className="py-2 border-b-2">Description</p>
        <p  className="py-2 border-b-2">Description</p>
        <p  className="py-2 border-b-2">MemoType</p>
        <p  className="py-2 border-b-2">Type the greeting and message text of the email.</p>
        <p  className="py-2 border-b-2">From</p>
        <p  className="py-2 border-b-2">from</p>
        <p  className="py-2 border-b-2">PartyListType</p>
        <p  className="py-2 border-b-2">Enter the sender of the email.</p>
        <p  className="py-2 border-b-2">Reminder Set</p>
        <p  className="py-2 border-b-2">IsEmailReminderSet</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">For internal use only. Shows whether this email Reminder is Set.</p>
        <p  className="py-2 border-b-2">Aktivitetskategori</p>
        <p  className="py-2 border-b-2">msys_ActivityCategory</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Medlem ved oprettelse</p>
        <p  className="py-2 border-b-2">msys_MemberOnCreate</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Queue</p>
        <p  className="py-2 border-b-2">msys_Queue</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Relevant kunde (teknisk felt)</p>
        <p  className="py-2 border-b-2">msys_RelevantKunde</p>
        <p  className="py-2 border-b-2">CustomerType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Til (kø)</p>
        <p  className="py-2 border-b-2">msys_ToQueue</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Hvis modtageren af emailen er en kø, peger dette felt på køen. Ellers er feltet tomt.</p>
        <p  className="py-2 border-b-2">Record Created On</p>
        <p  className="py-2 border-b-2">OverriddenCreatedOn</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Date and time that the record was migrated.</p>
        <p  className="py-2 border-b-2">Ejer</p>
        <p  className="py-2 border-b-2">OwnerId</p>
        <p  className="py-2 border-b-2">OwnerType</p>
        <p  className="py-2 border-b-2">Enter the user or team who is assigned to manage the record. This field is updated every time the record is assigned to a different user.</p>
        <p  className="py-2 border-b-2">Owning Business Unit</p>
        <p  className="py-2 border-b-2">OwningBusinessUnit</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Unique identifier of the business unit that owns the email activity.</p>
        <p  className="py-2 border-b-2">Owning Team</p>
        <p  className="py-2 border-b-2">OwningTeam</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Unique identifier of the team who owns the email activity.</p>
        <p  className="py-2 border-b-2">Owning User</p>
        <p  className="py-2 border-b-2">OwningUser</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Unique identifier of the user who owns the email activity.</p>
        <p  className="py-2 border-b-2">Priority</p>
        <p  className="py-2 border-b-2">PriorityCode</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2">Select the priority so that preferred customers or critical issues are handled quickly.</p>
        <p  className="py-2 border-b-2">Regarding</p>
        <p  className="py-2 border-b-2">RegardingObjectId</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Choose the record that the email relates to.</p>
        <p  className="py-2 border-b-2">Due Date</p>
        <p  className="py-2 border-b-2">ScheduledEnd</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Enter the expected due date and time for the activity to be completed to provide details about when the email will be sent.</p>
        <p  className="py-2 border-b-2">Start Date</p>
        <p  className="py-2 border-b-2">ScheduledStart</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Enter the expected start date and time for the activity to provide details about the tentative time when the email activity must be initiated.</p>
        <p  className="py-2 border-b-2">Date Sent</p>
        <p  className="py-2 border-b-2">SentOn</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Shows the date and time that the email was sent.</p>
        <p  className="py-2 border-b-2">SLA</p>
        <p  className="py-2 border-b-2">SLAId</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Choose the service level agreement (SLA) that you want to apply to the email record.</p>
        <p  className="py-2 border-b-2">Activity Status</p>
        <p  className="py-2 border-b-2">StateCode</p>
        <p  className="py-2 border-b-2">StateType</p>
        <p  className="py-2 border-b-2">Shows whether the email is open, completed, or canceled. Completed and canceled email is read-only and can't be edited.</p>
        <p  className="py-2 border-b-2">Status Reason</p>
        <p  className="py-2 border-b-2">StatusCode</p>
        <p  className="py-2 border-b-2">StatusType</p>
        <p  className="py-2 border-b-2">Select the email's status.</p>
        <p  className="py-2 border-b-2">Subject</p>
        <p  className="py-2 border-b-2">Subject</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type a short description about the objective or primary topic of the email.</p>
        <p  className="py-2 border-b-2">To</p>
        <p  className="py-2 border-b-2">to</p>
        <p  className="py-2 border-b-2">PartyListType</p>
        <p  className="py-2 border-b-2">Enter the account, contact, lead, queue, or user recipients for the email.</p>
        <p  className="py-2 border-b-2">To Recipients</p>
        <p  className="py-2 border-b-2">ToRecipients</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Shows the email addresses corresponding to the recipients.</p>
</Section>
<Section name="Fax">
        <p  className="py-2 border-b-2">Aktivitetskategori</p>
        <p  className="py-2 border-b-2">msys_ActivityCategory</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Medlem ved oprettelse</p>
        <p  className="py-2 border-b-2">msys_MemberOnCreate</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Subject</p>
        <p  className="py-2 border-b-2">Subject</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type a short description about the objective or primary topic of the fax.</p>
</Section>
<Section name="Letter">
        <p  className="py-2 border-b-2">Direction</p>
        <p  className="py-2 border-b-2">DirectionCode</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Select the direction of the letter as incoming or outbound.</p>
        <p  className="py-2 border-b-2">Aktivitetskategori</p>
        <p  className="py-2 border-b-2">msys_ActivityCategory</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Medlem ved oprettelse</p>
        <p  className="py-2 border-b-2">msys_MemberOnCreate</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Subject</p>
        <p  className="py-2 border-b-2">Subject</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type a short description about the objective or primary topic of the letter.</p>
</Section>
<Section name="msdyncrm_customerjourney">
        <p  className="py-2 border-b-2">Oprettet af</p>
        <p  className="py-2 border-b-2">CreatedBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the person who created this.</p>
        <p  className="py-2 border-b-2">Oprettelsesdato</p>
        <p  className="py-2 border-b-2">CreatedOn</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Date and time when the record was created</p>
        <p  className="py-2 border-b-2">Created by (delegate)</p>
        <p  className="py-2 border-b-2">CreatedOnBehalfBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the person who created this for another person.</p>
        <p  className="py-2 border-b-2">Modified by</p>
        <p  className="py-2 border-b-2">ModifiedBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the person who modified this.</p>
        <p  className="py-2 border-b-2">Modified on</p>
        <p  className="py-2 border-b-2">ModifiedOn</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Date and time when the record was modified</p>
        <p  className="py-2 border-b-2">Modified by (delegate)</p>
        <p  className="py-2 border-b-2">ModifiedOnBehalfBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the person who modified this for another person.</p>
        <p  className="py-2 border-b-2">Content settings</p>
        <p  className="py-2 border-b-2">msdyncrm_ContentSettingsId</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Content settings that apply to this customer journey</p>
        <p  className="py-2 border-b-2">Customer journey designer state</p>
        <p  className="py-2 border-b-2">msdyncrm_CustomerJourneyDesignerState</p>
        <p  className="py-2 border-b-2">MemoType</p>
        <p  className="py-2 border-b-2">The state of customer journey</p>
        <p  className="py-2 border-b-2">Customer journey</p>
        <p  className="py-2 border-b-2">msdyncrm_customerjourneyId</p>
        <p  className="py-2 border-b-2">UniqueidentifierType</p>
        <p  className="py-2 border-b-2">Unique ID for entity instances</p>
        <p  className="py-2 border-b-2">Customer journey template</p>
        <p  className="py-2 border-b-2">msdyncrm_CustomerJourneyTemplate</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">The template used to create the initial layout of the customer journey</p>
        <p  className="py-2 border-b-2">Time zone</p>
        <p  className="py-2 border-b-2">msdyncrm_CustomerJourneyTimeZone</p>
        <p  className="py-2 border-b-2">IntegerType</p>
        <p  className="py-2 border-b-2">Effective time zone for this customer journey</p>
        <p  className="py-2 border-b-2">Description</p>
        <p  className="py-2 border-b-2">msdyncrm_description</p>
        <p  className="py-2 border-b-2">MemoType</p>
        <p  className="py-2 border-b-2">Enter additional information to describe this customer journey</p>
        <p  className="py-2 border-b-2">End date and time</p>
        <p  className="py-2 border-b-2">msdyncrm_EndDateTime</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">The end date of customer journey</p>
        <p  className="py-2 border-b-2">Insights</p>
        <p  className="py-2 border-b-2">msdyncrm_insights_placeholder</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Name</p>
        <p  className="py-2 border-b-2">msdyncrm_name</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">The name of the customer journey</p>
        <p  className="py-2 border-b-2">Published by</p>
        <p  className="py-2 border-b-2">msdyncrm_publishedby</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the person who published this.</p>
        <p  className="py-2 border-b-2">Purpose</p>
        <p  className="py-2 border-b-2">msdyncrm_purpose</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Start date and time</p>
        <p  className="py-2 border-b-2">msdyncrm_StartDateTime</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">The start date of the customer journey</p>
        <p  className="py-2 border-b-2">Type</p>
        <p  className="py-2 border-b-2">msdyncrm_Type</p>
        <p  className="py-2 border-b-2">PicklistType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Error check results</p>
        <p  className="py-2 border-b-2">msdyncrm_ValidationResults</p>
        <p  className="py-2 border-b-2">MemoType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Record created on</p>
        <p  className="py-2 border-b-2">OverriddenCreatedOn</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Date and time that the record was migrated</p>
        <p  className="py-2 border-b-2">Ejer</p>
        <p  className="py-2 border-b-2">OwnerId</p>
        <p  className="py-2 border-b-2">OwnerType</p>
        <p  className="py-2 border-b-2">Owner ID</p>
        <p  className="py-2 border-b-2">Owning business unit</p>
        <p  className="py-2 border-b-2">OwningBusinessUnit</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the business unit that owns this.</p>
        <p  className="py-2 border-b-2">Owning team</p>
        <p  className="py-2 border-b-2">OwningTeam</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the team that owns this.</p>
        <p  className="py-2 border-b-2">Owning user</p>
        <p  className="py-2 border-b-2">OwningUser</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the person who owns this.</p>
        <p  className="py-2 border-b-2">Status</p>
        <p  className="py-2 border-b-2">statecode</p>
        <p  className="py-2 border-b-2">StateType</p>
        <p  className="py-2 border-b-2">Status of the customer journey</p>
        <p  className="py-2 border-b-2">Status reason</p>
        <p  className="py-2 border-b-2">statuscode</p>
        <p  className="py-2 border-b-2">StatusType</p>
        <p  className="py-2 border-b-2">Reason for the status of the customer journey</p>
</Section>
<Section name="msdyncrm_marketingemail">
        <p  className="py-2 border-b-2">Oprettet af</p>
        <p  className="py-2 border-b-2">CreatedBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the person who created this.</p>
        <p  className="py-2 border-b-2">Oprettelsesdato</p>
        <p  className="py-2 border-b-2">CreatedOn</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Date and time when the record was created</p>
        <p  className="py-2 border-b-2">Created by (delegate)</p>
        <p  className="py-2 border-b-2">CreatedOnBehalfBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the person who created this for another person.</p>
        <p  className="py-2 border-b-2">Modified by</p>
        <p  className="py-2 border-b-2">ModifiedBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the person who modified this.</p>
        <p  className="py-2 border-b-2">Modified on</p>
        <p  className="py-2 border-b-2">ModifiedOn</p>
        <p  className="py-2 border-b-2">DateTimeType</p>
        <p  className="py-2 border-b-2">Date and time when the record was modified</p>
        <p  className="py-2 border-b-2">Modified by (delegate)</p>
        <p  className="py-2 border-b-2">ModifiedOnBehalfBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the person who modified this for another person.</p>
        <p  className="py-2 border-b-2">Company address</p>
        <p  className="py-2 border-b-2">msdyncrm_contentsettingscompanyaddress</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Description</p>
        <p  className="py-2 border-b-2">msdyncrm_Description</p>
        <p  className="py-2 border-b-2">MemoType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Designer HTML</p>
        <p  className="py-2 border-b-2">msdyncrm_designerhtml</p>
        <p  className="py-2 border-b-2">MemoType</p>
        <p  className="py-2 border-b-2">Clean email body: HTML with no CSS inlining and no compression</p>
        <p  className="py-2 border-b-2">Email from address</p>
        <p  className="py-2 border-b-2">msdyncrm_FromEmail</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Email from name</p>
        <p  className="py-2 border-b-2">msdyncrm_FromName</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Marketing email</p>
        <p  className="py-2 border-b-2">msdyncrm_marketingemailId</p>
        <p  className="py-2 border-b-2">UniqueidentifierType</p>
        <p  className="py-2 border-b-2">Unique ID for entity instances</p>
        <p  className="py-2 border-b-2">Navn</p>
        <p  className="py-2 border-b-2">msdyncrm_Name</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Preview HTML</p>
        <p  className="py-2 border-b-2">msdyncrm_previewhtml</p>
        <p  className="py-2 border-b-2">MemoType</p>
        <p  className="py-2 border-b-2">Email body used only for preview display purposes</p>
        <p  className="py-2 border-b-2">Preview Text</p>
        <p  className="py-2 border-b-2">msdyncrm_previewtext</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">The preview (pre-header) text for marketing email</p>
        <p  className="py-2 border-b-2">Reply-to address</p>
        <p  className="py-2 border-b-2">msdyncrm_ReplyToEmail</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Emne</p>
        <p  className="py-2 border-b-2">msdyncrm_subject</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">The subject of the marketing email</p>
        <p  className="py-2 border-b-2">Email template</p>
        <p  className="py-2 border-b-2">msdyncrm_TemplateId</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Template for the email</p>
        <p  className="py-2 border-b-2">Test Configuration</p>
        <p  className="py-2 border-b-2">msdyncrm_testconfiguration</p>
        <p  className="py-2 border-b-2">MemoType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Plain text</p>
        <p  className="py-2 border-b-2">msdyncrm_textpart</p>
        <p  className="py-2 border-b-2">MemoType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Forening</p>
        <p  className="py-2 border-b-2">msys_Organizer</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Ejer</p>
        <p  className="py-2 border-b-2">OwnerId</p>
        <p  className="py-2 border-b-2">OwnerType</p>
        <p  className="py-2 border-b-2">Den medarbejder der har oprettet mailen. </p>
        <p  className="py-2 border-b-2">Owning business unit</p>
        <p  className="py-2 border-b-2">OwningBusinessUnit</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the business unit that owns this.</p>
        <p  className="py-2 border-b-2">Owning team</p>
        <p  className="py-2 border-b-2">OwningTeam</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the team that owns this.</p>
        <p  className="py-2 border-b-2">Owning user</p>
        <p  className="py-2 border-b-2">OwningUser</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Indicates the team that owns this.</p>
        <p  className="py-2 border-b-2">Status</p>
        <p  className="py-2 border-b-2">statecode</p>
        <p  className="py-2 border-b-2">StateType</p>
        <p  className="py-2 border-b-2">Status of the marketing email</p>
        <p  className="py-2 border-b-2">Mailstatus</p>
        <p  className="py-2 border-b-2">statuscode</p>
        <p  className="py-2 border-b-2">StatusType</p>
        <p  className="py-2 border-b-2">Marketing email status reason</p>
</Section>
<Section name="msdynmkt_journey">
        <p  className="py-2 border-b-2">Created By</p>
        <p  className="py-2 border-b-2">CreatedBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Unique identifier of the user who created the record.</p>
        <p  className="py-2 border-b-2">Created By (Delegate)</p>
        <p  className="py-2 border-b-2">CreatedOnBehalfBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Unique identifier of the delegate user who created the record.</p>
        <p  className="py-2 border-b-2">Modified By</p>
        <p  className="py-2 border-b-2">ModifiedBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Unique identifier of the user who modified the record.</p>
        <p  className="py-2 border-b-2">Modified By (Delegate)</p>
        <p  className="py-2 border-b-2">ModifiedOnBehalfBy</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Unique identifier of the delegate user who modified the record.</p>
        <p  className="py-2 border-b-2">Owner</p>
        <p  className="py-2 border-b-2">OwnerId</p>
        <p  className="py-2 border-b-2">OwnerType</p>
        <p  className="py-2 border-b-2">Owner Id</p>
        <p  className="py-2 border-b-2">Business Unit</p>
        <p  className="py-2 border-b-2">OwningBusinessUnit</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Unique identifier for the business unit that owns the record</p>
        <p  className="py-2 border-b-2">Owning Team</p>
        <p  className="py-2 border-b-2">OwningTeam</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Unique identifier for the team that owns the record.</p>
        <p  className="py-2 border-b-2">Owning User</p>
        <p  className="py-2 border-b-2">OwningUser</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Unique identifier for the user that owns the record.</p>
</Section>
<Section name="PhoneCall">
        <p  className="py-2 border-b-2">Direction</p>
        <p  className="py-2 border-b-2">DirectionCode</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Select the direction of the phone call as incoming or outbound.</p>
        <p  className="py-2 border-b-2">Call From</p>
        <p  className="py-2 border-b-2">from</p>
        <p  className="py-2 border-b-2">PartyListType</p>
        <p  className="py-2 border-b-2">Enter the account, contact, lead, or user who made the phone call.</p>
        <p  className="py-2 border-b-2">Aktivitetskategori</p>
        <p  className="py-2 border-b-2">msys_ActivityCategory</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Relevant kunde (teknisk felt)</p>
        <p  className="py-2 border-b-2">msys_CustomerTechnicalField</p>
        <p  className="py-2 border-b-2">CustomerType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Medlem ved oprettelse</p>
        <p  className="py-2 border-b-2">msys_MemberOnCreate</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2"></p>
        <p  className="py-2 border-b-2">Subject</p>
        <p  className="py-2 border-b-2">Subject</p>
        <p  className="py-2 border-b-2">StringType</p>
        <p  className="py-2 border-b-2">Type a short description about the objective or primary topic of the phone call.</p>
        <p  className="py-2 border-b-2">Call To</p>
        <p  className="py-2 border-b-2">to</p>
        <p  className="py-2 border-b-2">PartyListType</p>
        <p  className="py-2 border-b-2">Enter the account, contact, lead, or user recipients of the phone call.</p>
</Section>
<Section name="ProcessSession">
        <p  className="py-2 border-b-2">Regarding</p>
        <p  className="py-2 border-b-2">RegardingObjectId</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Unique ID of the object associated with the dialog session</p>
</Section>
<Section name="SyncError">
        <p  className="py-2 border-b-2">Record</p>
        <p  className="py-2 border-b-2">RegardingObjectId</p>
        <p  className="py-2 border-b-2">LookupType</p>
        <p  className="py-2 border-b-2">Choose the record that the sync error relates to.</p>
</Section>
<Section name="Template">
        <p  className="py-2 border-b-2">Send kalenderinvitation</p>
        <p  className="py-2 border-b-2">msys_CalendarInvite</p>
        <p  className="py-2 border-b-2">BooleanType</p>
        <p  className="py-2 border-b-2">Send kalenderinvitation med tilmeldingsbekræftelsen.</p>
</Section>
    </>
}

export default List
